VENDOR_ID = 0x04F3
PRODUCT_ID = 0x0C4C
SUPPORTED_VERSION = 3.05

# IO
ELAN_EP_CMD_IN = 0x01
ELAN_EP_CMD_OUT = 0x83

ERRORS = {
    0xFD: "ELAN_MSG_VERIFY_ERR",
    0xFB: "ELAN_MSG_DIRTY",
    0xFE: "ELAN_MSG_AREA_NOT_ENOUGH",
    0x41: "ELAN_MSG_TOO_HIGH",
    0x42: "ELAN_MSG_TOO_LEFT",
    0x43: "ELAN_MSG_TOO_LOW",
    0x44: "ELAN_MSG_TOO_RIGHT",
    0x00: "ELAN_MSG_OK",
}


if __name__ == "__main__":
    print(ERRORS[0x00])
